# updatecli.yaml
name: Example of Helm Chart resources

scms:
  helm-charts:
    kind: github
    spec:
      user: "updatecli-bot"
      email: "bot@updatecli.io"
      owner: "Dbaker1298"
      repository: "cnpg"
      token: "{{ requiredEnv .github.token }}"
      username: "Dbaker1298"
      branch: "main"
      commitmessage:
        type: "chore"
        title: "chore: update cloudnative-pg chart version"
        body: "updatecli: update cloudnative-pg chart version"
sources:
  chartRelease:
    kind: helmchart
    spec:
      url: https://cloudnative-pg.github.io/charts
      name: cloudnative-pg

conditions:
  isCloudnativepgHelmChartVersionAvailable:
    name: "Test if the cnpg helm chart is available"
    kind: helmchart
    spec:
      url: https://cloudnative-pg.github.io/charts
      name: cloudnative-pg
      version: "0.21.2"
    sourceid: chartRelease

targets:
  chartcloudnativepg:
    name: "Bump cnpg Chart Version"
    kind: helmchart
    spec:
      name: "package-management/cnpg-operator"
      file: "Chart.yaml"
      key: "$.dependencies[0].version"
      versionincrement: "patch,minor,major"
    sourceid: chartRelease
    scmid: helm-charts

actions:
  helm-charts:
    kind: "github/pullrequest"
    scmid: helm-charts
    spec:
      automerge: false
      title: "updatecli: update cloudnative-pg chart version"
      description: "updatecli: update cloudnative-pg chart version"