# updatecli.yaml
name: rancher-monitoring chart upgrade

pipelineid: "rancher-monitoring"

scms:
  helm-charts:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "bot@updatecli.io"
      owner: "Dbaker1298"
      repository: "cnpg"
      token: "{{ requiredEnv .github.token }}"
      username: "Dbaker1298"
      branch: "main"
      commitmessage:
        type: "chore"
        title: "chore: update rancher-monitoring chart version"
        body: "updatecli: update rancher-monitoring chart version"
sources:
  chartRelease:
    kind: helmchart
    spec:
      url: "https://charts.rancher.io"
      name: rancher-monitoring

conditions:
  isPreviousChartAvailable:
    name: "Is previous rancher-monitoring chart is available"
    kind: helmchart
    spec:
      url: "https://charts.rancher.io"
      name: rancher-monitoring
      version: "105.1.3+up61.3.2"
    sourceid: chartRelease

targets:
  chartcloudnativepg:
    name: "Bump rancher-monitoring Chart Version"
    kind: helmchart
    spec:
      name: ".github/package-management/rancher-monitoring"
      file: "Chart.yaml"
      key: "$.dependencies[0].version"
      versionincrement: "patch,minor,major"
    sourceid: chartRelease
    scmid: helm-charts

actions:
  helm-charts:
    kind: "github/pullrequest"
    scmid: helm-charts
    spec:
      automerge: false
      title: "chore: update rancher-monitoring chart version"
      description: "chore: update rancher-monitoring chart version"